# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=32, verbose_name='Apellido')),
                ('inscripto', models.BooleanField(default=False, verbose_name='Inscripto')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero Curso')),
                ('division', models.CharField(max_length=1, verbose_name='Division')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.Curso'),
        ),
    ]
